name: Generate songbook PDF

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: |
          sudo apt update && apt install make texlive-music python3
      - name: generate
        run: make
