name: Generate songbook PDF

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check out git repo
        uses: actions/checkout@v3
      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install make texlive-music texlive-lang-french texlive-latex-extra
      - name: Generate songbook
        run: make
