name: Generate songbook PDF

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repo
        uses: actions/checkout@v3
      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install make texlive-music texlive-lang-french texlive-latex-extra qrencode
      - name: Generate songbook
        run: |
          latex --version
          make
      - name: Create static files for github pages
        run: |
          cp -rv site _site
          cp -v build/songbook.pdf _site/
          qrencode https://etene.github.io/songbook/songbook.pdf -o _site/qrcode.png

      - name: Deploy pages artifact
        uses: actions/upload-pages-artifact@v2

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action